### ISSUE TITLE
better option to not convert short chains to IIAAFs

### ISSUE THREAD

**Issue by jedwards1211** [codemodsquad/asyncify#14]
Cases like
```js
const promises = Promise.all([
  user.update().then(() => user.reload()),
  post.update().then(() => post.reload()),
])
```
Would be better left alone since they become messy when converted to IIAAFs

**Comment by papb** [comment]
What's an IIAAF? :thinking:

**Comment by jedwards1211** [comment]
Immediately invoked async arrow function 😅
`(async () => ...)()`

**Comment by jedwards1211** [comment]
I forgot, this is more or less fixed, it no longer converts chains of length 2 or less where the handler is an arrow function expression
